- name: Set root password
  hosts: allovercloud
  any_errors_fatal: true
  gather_facts: false

  pre_tasks:
  - name: Wait for provisioned nodes to boot
    wait_for_connection:
      timeout: 600
      delay: 10

  tasks:
  - name: Set root password
    become: true
    user:
      name: root
      password: "Redhat123!@#"
