- name: Controller
  hostname_format: '%stackname%-controller-%index%'
  count: 3
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=2GB
          /var/log=4GB
          /var/log/audit=1GB
          /home=2GB
          /var=100%
    - playbook: /home/stack/templates/overcloud/set-root-password.yaml
  defaults:
    profile: control
    config_drive:
      cloud_config:
        chpasswd:
          list: |-
            root:openstack
          expire: False
    networks:
    - network: ctlplane
      vif: true
    - network: internal_api
      subnet: internal_api_subnet
    - network: tenant
      subnet: tenant_subnet
    - network: storage
      subnet: storage_subnet
    - network: storage_mgmt
      subnet: storage_mgmt_subnet
    - network: external
      subnet: external_subnet
    network_config:
      template: /home/stack/templates/01_overcloud_deployment_pre/nic-configs/controller.j2
      net_config_data_lookup:
        ctrl-0-ver17.1:
          nic1: 52:54:00:11:9f:0f
          nic2: 52:54:00:b3:bf:76
          nic3: 52:54:00:17:2c:df
        ctrl-1-ver17.1:
          nic1: 52:54:00:d9:74:1b
          nic2: 52:54:00:e2:c5:2d
          nic3: 52:54:00:59:65:16
        ctrl-2-ver17.1:
          nic1: 52:54:00:90:0e:4f
          nic2: 52:54:00:27:7e:1c
          nic3: 52:54:00:0b:91:ca
      default_route_network:
      - external
  instances:
  - hostname: rich-controller-0
    name: ctrl-0-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.42
    - network: internal_api
      fixed_ip: 172.24.1.42
    - network: tenant
      fixed_ip: 172.24.2.42
    - network: storage
      fixed_ip: 172.24.3.42
    - network: storage_mgmt
      fixed_ip: 172.24.4.42
    - network: external
      fixed_ip: 10.8.60.186
  - hostname: rich-controller-1
    name: ctrl-1-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.43
    - network: internal_api
      fixed_ip: 172.24.1.43
    - network: tenant
      fixed_ip: 172.24.2.43
    - network: storage
      fixed_ip: 172.24.3.43
    - network: storage_mgmt
      fixed_ip: 172.24.4.43
    - network: external
      fixed_ip: 10.8.60.187
  - hostname: rich-controller-2
    name: ctrl-2-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.44
    - network: internal_api
      fixed_ip: 172.24.1.44
    - network: tenant
      fixed_ip: 172.24.2.44
    - network: storage
      fixed_ip: 172.24.3.44
    - network: storage_mgmt
      fixed_ip: 172.24.4.44
    - network: external
      fixed_ip: 10.8.60.188
- name: Compute
  hostname_format: '%stackname%-novacompute-%index%'
  count: 2
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=2GB
          /var/log=4GB
          /var/log/audit=1GB
          /home=2GB
          /var=100%
    - playbook: /home/stack/templates/overcloud/set-root-password.yaml
  defaults:
    profile: compute
    config_drive:
      cloud_config:
        chpasswd:
          list: |-
            root:openstack
          expire: False
    networks:
    - network: ctlplane
      vif: true
    - network: internal_api
      subnet: internal_api_subnet
    - network: tenant
      subnet: tenant_subnet
    - network: storage
      subnet: storage_subnet
    - network: external
      subnet: external_subnet
    network_config:
      template: /home/stack/templates/01_overcloud_deployment_pre/nic-configs/compute.j2
      net_config_data_lookup:
        cmp-0-ver17.1:
          nic1: 52:54:00:74:9b:0e
          nic2: 52:54:00:2c:a0:4b
          nic3: 52:54:00:41:b1:f3
        cmp-1-ver17.1:
          nic1: 52:54:00:ce:63:85
          nic2: 52:54:00:0f:fd:1f
          nic3: 52:54:00:f7:f0:95
      default_route_network:
      - external
  instances:
  - hostname: rich-compute-0
    name: cmp-0-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.45
    - network: internal_api
      fixed_ip: 172.24.1.45
    - network: tenant
      fixed_ip: 172.24.2.45
    - network: storage
      fixed_ip: 172.24.3.45
    - network: external
      fixed_ip: 10.8.60.189
  - hostname: rich-compute-1
    name: cmp-1-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.46
    - network: internal_api
      fixed_ip: 172.24.1.46
    - network: tenant
      fixed_ip: 172.24.2.46
    - network: storage
      fixed_ip: 172.24.3.46
    - network: external
      fixed_ip: 10.8.60.190