- name: Controller
  hostname_format: '%stackname%-controller-%index%'
  count: 3
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=2GB
          /var/log=4GB
          /var/log/audit=1GB
          /home=2GB
          /var=100%
    - playbook: /home/stack/templates/overcloud/set-root-password.yaml
  defaults:
    profile: control
    config_drive:
      cloud_config:
        chpasswd:
          list: |-
            root:openstack
          expire: False
    networks:
    - network: ctlplane
      vif: true
    - network: internal_api
      subnet: internal_api_subnet
    - network: tenant
      subnet: tenant_subnet
    - network: storage
      subnet: storage_subnet
    - network: storage_mgmt
      subnet: storage_mgmt_subnet
    - network: external
      subnet: external_subnet
    network_config:
      template: /home/stack/templates/01_overcloud_deployment_pre/nic-configs/controller.j2
      net_config_data_lookup:
        ctrl-0-ver17.1:
          nic1: 52:54:00:13:f8:b0
          nic2: 52:54:00:54:b9:0c
          nic3: 52:54:00:3a:73:27
        ctrl-1-ver17.1:
          nic1: 52:54:00:26:bd:8d
          nic2: 52:54:00:c9:dc:ed
          nic3: 52:54:00:ba:4d:63
        ctrl-2-ver17.1:
          nic1: 52:54:00:b0:b5:bf
          nic2: 52:54:00:e5:99:38
          nic3: 52:54:00:77:21:cd
      default_route_network:
      - external
  instances:
  - hostname: rich-controller-0
    name: ctrl-0-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.47
    - network: internal_api
      fixed_ip: 172.24.1.47
    - network: tenant
      fixed_ip: 172.24.2.47
    - network: storage
      fixed_ip: 172.24.3.47
    - network: storage_mgmt
      fixed_ip: 172.24.4.47
    - network: external
      fixed_ip: 10.8.60.197
  - hostname: rich-controller-1
    name: ctrl-1-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.48
    - network: internal_api
      fixed_ip: 172.24.1.48
    - network: tenant
      fixed_ip: 172.24.2.48
    - network: storage
      fixed_ip: 172.24.3.48
    - network: storage_mgmt
      fixed_ip: 172.24.4.48
    - network: external
      fixed_ip: 10.8.60.187
  - hostname: rich-controller-2
    name: ctrl-2-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.49
    - network: internal_api
      fixed_ip: 172.24.1.49
    - network: tenant
      fixed_ip: 172.24.2.49
    - network: storage
      fixed_ip: 172.24.3.49
    - network: storage_mgmt
      fixed_ip: 172.24.4.49
    - network: external
      fixed_ip: 10.8.60.188
- name: Compute
  hostname_format: '%stackname%-novacompute-%index%'
  count: 2
  ansible_playbooks:
    - playbook: /usr/share/ansible/tripleo-playbooks/cli-overcloud-node-growvols.yaml
      extra_vars:
        growvols_args: >
          /=8GB
          /tmp=2GB
          /var/log=4GB
          /var/log/audit=1GB
          /home=2GB
          /var=100%
    - playbook: /home/stack/templates/overcloud/set-root-password.yaml
  defaults:
    profile: compute
    config_drive:
      cloud_config:
        chpasswd:
          list: |-
            root:openstack
          expire: False
    networks:
    - network: ctlplane
      vif: true
    - network: internal_api
      subnet: internal_api_subnet
    - network: tenant
      subnet: tenant_subnet
    - network: storage
      subnet: storage_subnet
    - network: external
      subnet: external_subnet
    network_config:
      template: /home/stack/templates/01_overcloud_deployment_pre/nic-configs/compute.j2
      net_config_data_lookup:
        cmp-0-ver17.1:
          nic1: 52:54:00:51:09:a8
          nic2: 52:54:00:d0:02:47
          nic3: 52:54:00:96:35:5b
        cmp-1-ver17.1:
          nic1: 52:54:00:ad:12:88
          nic2: 52:54:00:a0:81:35
          nic3: 52:54:00:82:4e:98
      default_route_network:
      - external
  instances:
  - hostname: rich-compute-0
    name: cmp-0-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.50
    - network: internal_api
      fixed_ip: 172.24.1.52
    - network: tenant
      fixed_ip: 172.24.2.52
    - network: storage
      fixed_ip: 172.24.3.52
    - network: external
      fixed_ip: 10.8.60.189
  - hostname: rich-compute-1
    name: cmp-1-ver17.1
    networks:
    - network: ctlplane
      vif: true
      fixed_ip: 10.2.3.51
    - network: internal_api
      fixed_ip: 172.24.1.51
    - network: tenant
      fixed_ip: 172.24.2.51
    - network: storage
      fixed_ip: 172.24.3.51
    - network: external
      fixed_ip: 10.8.60.190
